CREATE DATABASE IF NOT EXISTS customer_behavior_db;
USE customer_behavior_db;

SHOW DATABASES;

USE customer_behavior_db;

SELECT COUNT(*) FROM customer_shopping_behavior;

#Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY gender;

#Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

#Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, AVG(review_rating) AS avg_review_rating
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

#Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount) AS avg_purchase_amount
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

#Q5. Do subscribed customers spend more? Compare average spend and total revenue 
SELECT
    subscription_status,
    AVG(purchase_amount) AS avg_spend,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status;
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
     / COUNT(*)) AS discount_percentage
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

#Q7. Segment customers into New, Returning, and Loyal based on their total ?
SELECT
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behavior;

#Q8. What are the top 3 most purchased products within each category? 
SELECT
    customer_id,
    previous_purchases,
    CASE
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behavior;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    subscription_status,
    COUNT(*) AS customer_count
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

#Q10. What is the revenue contribution of each age group? 
SELECT
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue DESC;







